const products=[
{id:'frame-chair',name:'Frame Lounge Chair',category:'living',material:'Upholstery, painted oak',price:680,badge:'Bestseller',image:'assets/products/frame-chair-natural.jpg',variants:{Natural:'assets/products/frame-chair-natural.jpg',Dark:'assets/products/frame-chair-dark.png'},description:'A compact lounge chair with a deeply buttoned seat and turned oak legs.',details:['Upholstered seat and back','Painted solid oak legs','W 72 x D 70 x H 86 cm']},
{id:'pivot-light',name:'Pivot Task Light',category:'workspace',material:'Powder-coated steel',price:240,badge:'',image:'assets/products/pivot-light-natural.jpg',variants:{Graphite:'assets/products/pivot-light-natural.jpg',Black:'assets/products/pivot-light-dark.png'},description:'A precise adjustable task light with a broad shade and focused illumination.',details:['Powder-coated steel','Adjustable shade','H 126 cm, 2 m cord']},
{id:'still-vessel',name:'Still Coffee Table',category:'living',material:'Glass, solid beech',price:415,badge:'New',image:'assets/products/still-vessel-natural.jpg',description:'A slim glass-topped table with tapered solid-wood legs for smaller living spaces.',details:['Polished glass top','Solid beech legs','W 82 x D 48 x H 42 cm']},
{id:'line-desk',name:'Line Writing Desk',category:'workspace',material:'Plywood, powder-coated steel',price:920,badge:'',image:'assets/products/line-desk-natural.jpg',description:'A generous adjustable writing desk designed for focused work and cable-free surfaces.',details:['Birch plywood top','Height-adjustable steel base','W 145 x D 75 cm']},
{id:'fold-stool',name:'Fold Side Stool',category:'living',material:'Oiled walnut',price:310,badge:'',image:'assets/products/fold-stool-natural.jpg',variants:{Natural:'assets/products/fold-stool-natural.jpg',Dark:'assets/products/fold-stool-dark.png'},description:'A small, versatile stool with intersecting planes and softened hand-finished edges.',details:['Solid American walnut','Natural hard-wax oil','W 38 x D 32 x H 44 cm']},
{id:'arc-lamp',name:'Dome Pendant Lamp',category:'living',material:'Powder-coated aluminium',price:340,badge:'Low stock',image:'assets/products/arc-lamp-natural.jpg',variants:{Stone:'assets/products/arc-lamp-natural.jpg',Black:'assets/products/dome-pendant-dark.png'},description:'A simple pendant with a broad shade that casts warm, focused light over a table.',details:['Powder-coated aluminium','Warm white diffuser','Shade 42 cm, 2 m cord']},
{id:'field-tray',name:'Cane Sideboard',category:'living',material:'Oak, woven cane',price:1280,badge:'',image:'assets/products/field-tray-natural.jpg',description:'A low storage cabinet with woven cane fronts and a warm natural oak frame.',details:['Solid oak and oak veneer','Woven cane door fronts','W 180 x D 44 x H 72 cm']},
{id:'column-shelf',name:'Column Shelving System',category:'workspace',material:'Solid oak',price:1460,badge:'New',image:'assets/products/column-shelf-natural.jpg',description:'A wall-length modular shelving system with varied bays for books and objects.',details:['Solid European oak','Modular bay construction','Configured to order']}
];
const articles={
'room-better-with-use':{topic:'Spaces',time:'8 min read',date:'September 4, 2026',title:'How to build a room that gets better with use',dek:'Start with proportion and daily movement, then choose materials that can carry evidence of a life well lived.',image:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1800&q=88',alt:'Warm, layered living room with natural materials',intro:'The most enduring rooms rarely begin with a shopping list. They begin with an honest account of how the room needs to work.',sections:[['Begin with movement','Notice the paths people take through the space, where they pause, and what they reach for. Protect those routes before adding furniture. A room feels calm when movement through it is obvious and unforced.'],['Let materials record time','Oiled timber, woven fibres, and honest metals can be maintained rather than disguised. Small changes in tone and texture become part of the object, not a reason to replace it.'],['Choose one visual anchor','Give the eye one strong place to rest, then allow the remaining pieces to support it. Balance is usually more useful than perfect symmetry.']]},
'walnut-repairable-surface':{topic:'Materials',time:'5 min read',date:'August 21, 2026',title:'Walnut, oil, and the value of a repairable surface',dek:'Why a finish designed to change can be more useful than one designed to remain untouched.',image:'assets/products/fold-stool-natural.jpg',alt:'Oiled walnut side stool',intro:'A useful finish is not the one that promises never to change. It is the one that can be understood, maintained, and renewed.',sections:[['Oil works with the timber','An oil finish sits within the grain instead of creating a hard shell above it. The surface remains tactile and small marks can be treated locally.'],['Care should be ordinary','A soft cloth, prompt attention to spills, and occasional re-oiling are enough for most pieces. Maintenance should fit normal life.'],['Patina is information','Changes in colour show where an object is held and used. That record can make a well-built piece feel more personal over time.']]},
'three-layers-of-light':{topic:'Practice',time:'6 min read',date:'August 8, 2026',title:'Three layers of light for focused work',dek:'A practical balance of daylight, ambient light, and a precise source at the desk.',image:'assets/products/pivot-light-natural.jpg',alt:'Adjustable graphite task lamp',intro:'Good workspace lighting is layered. No single fitting needs to solve the whole room.',sections:[['Use daylight as the base','Place the desk beside a window rather than directly in front of it. Side light limits screen glare while keeping the wider room connected to the day.'],['Keep ambient light soft','A broad ceiling or wall source reduces harsh contrast after dark. It should make the room legible without flattening it.'],['Aim task light precisely','An adjustable lamp belongs opposite the writing hand and below eye level. Light the work, not the person.']]},
'small-room-proportion':{topic:'Spaces',time:'4 min read',date:'July 24, 2026',title:'The small-room rule: proportion before style',dek:'How circulation, negative space, and visual weight make a compact room feel settled.',image:'assets/products/still-vessel-natural.jpg',alt:'Coffee table in a compact living room',intro:'In a compact room, every object participates in the architecture. Its visual weight matters as much as its measurements.',sections:[['Measure the empty space','Plan the passages between objects first. Comfortable circulation makes a smaller room feel generous.'],['Lower the visual horizon','A lower table and an open-legged chair keep more wall visible and reduce the sense of crowding.'],['Repeat one material','A restrained material palette connects separate functions without adding visual noise.']]},
'designing-workday':{topic:'Practice',time:'7 min read',date:'July 10, 2026',title:'Designing a desk around the workday',dek:'Map the tasks first. The right surface, storage, and lighting decisions follow naturally.',image:'assets/products/line-desk-natural.jpg',alt:'Writing desk in a bright workspace',intro:'The best workspace is not a styled photograph. It is a sequence of small decisions that reduce friction throughout the day.',sections:[['List the real tasks','Writing, calls, sketching, and focused screen work ask different things of a surface. Make room for the repeated tasks first.'],['Control the cables','Route power before placing accessories. A clear surface is easier to maintain when cables already have an intentional path.'],['Make stopping easy','A tray, drawer, or shelf for unfinished work creates a visible end to the day without requiring a complete reset.']]},
'responsible-cane':{topic:'Materials',time:'5 min read',date:'June 26, 2026',title:'What responsible cane construction looks like',dek:'From tension and framing to the simple maintenance that keeps woven panels working.',image:'assets/products/field-tray-natural.jpg',alt:'Oak sideboard with woven cane fronts',intro:'Woven cane is light, strong, and renewable, but its performance depends on careful framing and consistent tension.',sections:[['The frame carries the load','Cane panels should not replace structural joinery. A stable timber frame protects the weave from twisting.'],['Even tension matters','A consistent pattern distributes pressure and prevents local sagging. The edges should be cleanly secured and easy to inspect.'],['Humidity needs balance','Cane responds to moisture. Avoid direct heat, clean it gently, and allow normal room humidity to keep the fibres resilient.']]},
'shelving-as-architecture':{topic:'Spaces',time:'6 min read',date:'June 12, 2026',title:'When shelving becomes architecture',dek:'A modular system can organise a wall, define a room, and change as the household does.',image:'assets/products/column-shelf-natural.jpg',alt:'Wall-length oak shelving system',intro:'Large shelving does more than hold objects. It establishes rhythm, scale, and a useful edge to the room.',sections:[['Start with the wall','Map doors, sockets, switches, and sightlines before choosing bay sizes. The system should clarify the wall rather than fight it.'],['Mix open and quiet zones','Books and objects benefit from varied spacing. Closed or sparsely used sections give the composition room to breathe.'],['Plan for change','Adjustable shelves and repeatable modules let the system respond to new uses without becoming disposable.']]}
};
const $=(s,n=document)=>n.querySelector(s),$$=(s,n=document)=>[...n.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
let stored=[];try{stored=JSON.parse(localStorage.getItem('atelier-cart')||'[]')}catch{};
const state={filter:'all',sort:'featured',cart:Array.isArray(stored)?stored:[]};let toastTimer;
function installCommerce(){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" data-overlay hidden></div><aside class="drawer" data-cart-drawer aria-label="Shopping bag" aria-hidden="true"><div class="drawer__head"><div><p class="edition">Your selection</p><h2>Shopping bag</h2></div><button class="icon-button" type="button" data-close-cart aria-label="Close shopping bag">x</button></div><div class="cart-lines" data-cart-lines></div><div class="cart-empty" data-cart-empty><h3>Your bag is empty.</h3><p>Explore the collection and save an object here.</p><a class="button button--secondary" href="catalog.html">Explore the catalog</a></div><div class="cart-summary" data-cart-summary hidden><div><span>Subtotal</span><strong data-cart-total>$0</strong></div><p>Complimentary shipping over $120. Taxes calculated at checkout.</p><button class="button button--primary button--wide" type="button" data-checkout>Continue to checkout</button></div></aside><section class="search-panel" data-search-panel aria-label="Search products" aria-hidden="true"><div class="search-panel__head"><label>Search the collection<input type="search" placeholder="Try oak, lighting, workspace" data-search-input></label><button class="icon-button" type="button" data-close-search aria-label="Close search">x</button></div><div class="search-results" data-search-results><p>Start typing to search eight selected objects.</p></div></section><dialog class="checkout-dialog" data-checkout-dialog><button class="icon-button dialog-close" type="button" data-close-checkout aria-label="Close checkout">x</button><div class="checkout-copy"><p class="edition">Demo checkout</p><h2>Complete your sample order.</h2><p>No payment, order, or personal data will be transmitted.</p></div><form data-checkout-form><div class="field-row"><label>First name<input required></label><label>Last name<input required></label></div><label>Email<input required type="email"></label><label>Delivery country<select><option>United States</option><option>United Kingdom</option><option>European Union</option></select></label><label>Address<input required placeholder="Demo address only"></label><button class="button button--primary button--wide" type="submit">Place simulated order</button></form></dialog><div class="toast" role="status" aria-live="polite"></div>`)}
installCommerce();
const els={count:$$('[data-cart-count]'),drawer:$('[data-cart-drawer]'),overlay:$('[data-overlay]'),lines:$('[data-cart-lines]'),empty:$('[data-cart-empty]'),summary:$('[data-cart-summary]'),total:$('[data-cart-total]'),search:$('[data-search-panel]'),searchInput:$('[data-search-input]'),searchResults:$('[data-search-results]'),checkout:$('[data-checkout-dialog]'),toast:$('.toast')};
function save(){localStorage.setItem('atelier-cart',JSON.stringify(state.cart))}
function notify(m){els.toast.textContent=m;els.toast.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('is-visible'),2600)}
function productCard(p){return `<article class="product"><a class="product__image" href="product.html?id=${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span>${p.badge}</span>`:''}</a><div class="product__meta"><a href="product.html?id=${p.id}"><h3>${p.name}</h3><p>${p.material}</p></a><strong>${money(p.price)}</strong></div><button class="product__add" type="button" data-add="${p.id}">Add to bag</button></article>`}
function listProducts(){let list=products.filter(p=>state.filter==='all'||p.category===state.filter);if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);return list}
function renderProducts(){const grid=$('[data-product-grid]');if(!grid)return;let list=listProducts();const limit=Number(grid.dataset.limit||0);if(limit)list=list.slice(0,limit);grid.innerHTML=list.map(productCard).join('');const count=$('[data-result-count]');if(count)count.textContent=list.length;bindAdds()}
function bindAdds(){$$('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add,1,b.dataset.finish)))}
function addToCart(id,quantity=1,finish){const p=products.find(x=>x.id===id);const chosen=finish||Object.keys(p.variants||{})[0]||'Standard';const item=state.cart.find(x=>x.id===id&&x.finish===chosen);item?item.quantity+=quantity:state.cart.push({id,quantity,finish:chosen});renderCart();notify(`${p.name} added to the demo bag.`)}
function renderCart(){const total=state.cart.reduce((s,x)=>s+x.quantity,0);els.count.forEach(x=>x.textContent=total);els.lines.innerHTML=state.cart.map((x,i)=>{const p=products.find(y=>y.id===x.id),image=p.variants?.[x.finish]||p.image;return `<article class="cart-line"><img src="${image}" alt=""><div><h3>${p.name}</h3><p>${x.finish} finish</p><div class="quantity"><button data-qty="${i}" data-delta="-1">-</button><span>${x.quantity}</span><button data-qty="${i}" data-delta="1">+</button></div></div><strong>${money(p.price*x.quantity)}</strong></article>`}).join('');els.empty.hidden=state.cart.length>0;els.summary.hidden=!state.cart.length;els.total.textContent=money(state.cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.quantity,0));save();$$('[data-qty]').forEach(b=>b.addEventListener('click',()=>{const x=state.cart[+b.dataset.qty];x.quantity+=+b.dataset.delta;if(x.quantity<1)state.cart.splice(+b.dataset.qty,1);renderCart()}))}
function openLayer(x){els.overlay.hidden=false;requestAnimationFrame(()=>{els.overlay.classList.add('is-visible');x.classList.add('is-open');x.setAttribute('aria-hidden','false')});document.body.classList.add('locked')}
function closeLayers(){els.overlay.classList.remove('is-visible');[els.drawer,els.search].forEach(x=>{x.classList.remove('is-open');x.setAttribute('aria-hidden','true')});document.body.classList.remove('locked');setTimeout(()=>els.overlay.hidden=true,220)}
function renderSearch(q=''){const term=q.trim().toLowerCase();if(!term){els.searchResults.innerHTML='<p>Start typing to search eight selected objects.</p>';return}const found=products.filter(p=>`${p.name} ${p.material} ${p.category}`.toLowerCase().includes(term));els.searchResults.innerHTML=found.length?found.map(p=>`<a href="product.html?id=${p.id}"><img src="${p.image}" alt=""><span><strong>${p.name}</strong><small>${p.material}</small></span><b>${money(p.price)}</b></a>`).join(''):'<div class="no-results"><h3>No objects found.</h3><p>Try oak, lighting, living, or workspace.</p></div>'}
function finishOptions(p,selected){const names=Object.keys(p.variants||{});if(!names.length)return '<p class="single-finish"><span>Finish</span><strong>Standard</strong></p>';return `<fieldset class="finish-picker"><legend>Finish</legend><div class="finish-options" role="radiogroup">${names.map(n=>`<button class="finish-option${n===selected?' is-selected':''}" type="button" role="radio" aria-checked="${n===selected}" data-finish="${n}"><span class="finish-swatch finish-swatch--${n.toLowerCase()}"></span><span>${n}</span><span class="finish-check">✓</span></button>`).join('')}</div></fieldset>`}
function renderProductPage(){const root=$('[data-product-page]');if(!root)return;const p=products.find(x=>x.id===new URLSearchParams(location.search).get('id'))||products[0];let selected=Object.keys(p.variants||{})[0]||'Standard';root.innerHTML=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><a href="catalog.html">Catalog</a><span>/</span><span>${p.name}</span></nav><div class="product-page__grid"><div class="product-page__media"><img src="${p.image}" alt="${p.name}" data-detail-image><p>Selected objects photographed in a quiet residential setting.</p></div><div class="product-page__copy"><p class="edition">${p.category}</p><h1>${p.name}</h1><p class="product-price">${money(p.price)}</p><p class="lead">${p.description}</p><div data-finish-root>${finishOptions(p,selected)}</div><button class="button button--primary button--wide" type="button" data-product-add>Add to bag</button><details open><summary>Materials and dimensions</summary><ul>${p.details.map(x=>`<li>${x}</li>`).join('')}</ul></details><details><summary>Delivery and returns</summary><p>Dispatches within 48 hours. Complimentary delivery and 30-day returns.</p></details></div></div>`;$$('[data-finish]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.finish;$$('[data-finish]').forEach(x=>{x.classList.toggle('is-selected',x===b);x.setAttribute('aria-checked',String(x===b))});$('[data-detail-image]').src=p.variants[selected]}));$('[data-product-add]').addEventListener('click',()=>{addToCart(p.id,1,selected);openLayer(els.drawer)})}
function renderArticlePage(){const root=$('[data-article-page]');if(!root)return;const key=new URLSearchParams(location.search).get('id');const a=articles[key]||articles['room-better-with-use'];root.innerHTML=`<article class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><a href="journal.html">Journal</a><span>/</span><span>${a.topic}</span></nav><header class="article__header"><p class="edition">${a.topic} · ${a.time}</p><h1>${a.title}</h1><p>${a.dek}</p><div class="story-meta"><span>${a.date}</span><span>By The Atelier team</span></div></header><figure class="article__hero"><img src="${a.image}" alt="${a.alt}"><figcaption>A fictional editorial image used for this portfolio demonstration.</figcaption></figure><div class="article__body"><p class="article__intro">${a.intro}</p>${a.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}<aside><p class="edition">From the collection</p><h2>Objects chosen for use, care, and a long life.</h2><a class="button button--primary" href="catalog.html">Explore the catalog</a></aside><a class="article__back" href="journal.html">← Back to all stories</a></div></article>`}
$('.menu-button')?.addEventListener('click',e=>{const open=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!open));$('#primary-nav').classList.toggle('is-open',!open)});
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');state.filter=b.dataset.filter;renderProducts()}));
$('[data-sort]')?.addEventListener('change',e=>{state.sort=e.target.value;renderProducts()});
$$('[data-open-cart]').forEach(b=>b.addEventListener('click',()=>openLayer(els.drawer)));$$('[data-close-cart]').forEach(b=>b.addEventListener('click',closeLayers));
$$('[data-open-search]').forEach(b=>b.addEventListener('click',()=>{openLayer(els.search);setTimeout(()=>els.searchInput.focus(),220)}));$('[data-close-search]').addEventListener('click',closeLayers);els.overlay.addEventListener('click',closeLayers);els.searchInput.addEventListener('input',e=>renderSearch(e.target.value));
$('[data-checkout]').addEventListener('click',()=>{closeLayers();els.checkout.showModal()});$('[data-close-checkout]').addEventListener('click',()=>els.checkout.close());$('[data-checkout-form]').addEventListener('submit',e=>{e.preventDefault();els.checkout.close();state.cart=[];renderCart();notify('Simulated order complete. No payment or order was created.')});
$$('[data-newsletter],[data-contact-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();form.reset();notify(form.hasAttribute('data-contact-form')?'Demo inquiry saved locally. Nothing was sent.':'Demo signup saved locally. No email was sent.')}));
renderProducts();renderProductPage();renderArticlePage();if($('[data-article-page]')){const article=articles[new URLSearchParams(location.search).get('id')]||articles['room-better-with-use'];document.title=`${article.title} | Atelier Supply`}renderCart();
