const journalBodies={
'room-better-with-use':[
{heading:'Begin with movement, not furniture',paragraphs:['Before choosing a chair or table, spend time observing the room empty. Mark the routes between doors, windows, storage, and the places where people naturally stop. A comfortable path needs enough width to feel obvious, but it should not divide the room into disconnected islands. When movement is resolved first, furniture can support the plan instead of constantly interrupting it.','Daily habits are equally useful evidence. A reading chair needs a surface within reach. A dining table needs clearance when every seat is occupied. A hallway needs a place for the objects that actually arrive through the door. Designing around repeated actions produces a room that feels calm because fewer decisions have to be made each day.']},
{heading:'Set the visual weight',paragraphs:['Measurements explain whether an object fits, but visual weight explains how it feels in the room. A solid cabinet occupies more attention than an open shelving system of the same size. Upholstery absorbs light, while glass and slender legs allow the eye to continue through the object. Combine heavier and lighter forms so that no single edge of the room feels overloaded.','Choose one visual anchor and let the remaining pieces play supporting roles. The anchor might be a generous sofa, a long table, or a wall of books. It does not need to be colourful or dramatic. It simply needs enough scale and presence to organise the view. Repetition in timber tone, line, or height can then connect the quieter pieces.']},
{heading:'Choose materials that can carry time',paragraphs:['A room that improves with use depends on surfaces that can be maintained. Oiled timber can be cleaned and renewed. Wool softens while keeping its structure. Good metal develops small changes in tone without losing its function. These materials do not remain untouched, but their ageing process is understandable and usually repairable.','Ask practical questions before buying. Can a finish be renewed locally? Can a cover be removed? Are fixings accessible? Is the material appropriate beside a window, radiator, or busy entrance? Honest answers matter more than broad claims about durability. Longevity is created by the relationship between material, construction, placement, and care.']},
{heading:'Leave the room some reserve',paragraphs:['Not every wall needs a cabinet and not every corner needs a chair. Empty space gives useful objects definition and keeps a room adaptable. It also makes cleaning easier, improves daylight, and leaves room for the household to change. A finished room should still have capacity rather than appearing permanently full.','Add objects in stages. Live with the main pieces, notice where the room still creates friction, and solve only those problems. This slower sequence reduces duplicate storage, decorative filler, and purchases made to complete a photograph rather than support a life.']},
{heading:'A useful final check',paragraphs:['Walk through the room at the busiest time of day. Sit in every seat, open every door, switch on each light, and reach for the things used most often. If an action requires moving another object, the arrangement is not finished. If the room works without explanation, it is close.','The result may be quieter than an instantly impressive interior. That is often a strength. A well-resolved room makes ordinary routines easier, gives good materials space to age, and remains open to new uses without needing to be redesigned from the beginning.']}
],
'walnut-repairable-surface':[
{heading:'What gives walnut its character',paragraphs:['Walnut is valued for colour that ranges from pale brown to deep chocolate, often within a single board. The grain is usually calm but never completely uniform. Responsible makers arrange boards with attention to tone and direction rather than hiding every variation. Those differences are part of the material, not defects that need to be printed over.','Freshly worked walnut can look cooler and darker than a finished piece. Exposure to daylight gradually softens the contrast and brings warmer notes forward. This process is normal. Moving small objects occasionally during the first months helps the surface change more evenly.']},
{heading:'Why oil works with the timber',paragraphs:['A penetrating oil sits within the fibres instead of forming a thick plastic-like film above them. The hand can still read the grain, and small scratches are less likely to appear as sharp white lines. When the surface becomes dry or uneven, a limited area can often be cleaned, lightly prepared, and treated again.','Film finishes can offer stronger resistance to spills, but repair may require stripping and refinishing a much larger area. Neither system is universally better. For a tactile side table or stool, oil provides a useful balance of protection, natural feel, and realistic maintenance.']},
{heading:'A simple care routine',paragraphs:['For ordinary cleaning, use a soft dry cloth or one that is only slightly damp. Wipe spills promptly and avoid household sprays containing silicone, bleach, or strong solvents. Wet glasses and plant pots should sit on a coaster or tray because repeated moisture is more damaging than a single carefully cleaned spill.','When the timber begins to look pale or rough, follow the maker’s instructions for maintenance oil. Test an inconspicuous area first, work with the grain, and remove every trace of excess product. More oil is not more protection. A thin, even application that cures fully produces the most reliable surface.']},
{heading:'Repair before replacement',paragraphs:['A shallow scratch may need no treatment beyond time and normal handling. For a more visible mark, clean the area and assess whether the fibres are cut or merely compressed. Local sanding should be cautious because it can create a lighter patch. The goal is to make the damage less distracting, not erase every sign of use.','Loose joints, movement, or cracks require a furniture repair specialist rather than cosmetic treatment. Early intervention protects the surrounding timber and usually keeps the repair small. Accessible construction and replaceable components are therefore as important as the finish itself.']},
{heading:'Patina as a record of use',paragraphs:['A well-maintained walnut object becomes more specific to its owner. Edges soften, frequently touched areas gain a subtle polish, and colour settles in response to the room. Patina is different from neglect: the surface remains clean, stable, and functional while recording ordinary contact.','Choosing a repairable finish changes the relationship with the object. Care becomes occasional and understandable, damage becomes a solvable event, and the piece can remain useful long after a sealed surface would have been considered worn out.']}
],
'three-layers-of-light':[
{heading:'Start with daylight',paragraphs:['Daylight provides colour accuracy, alertness, and a changing sense of time. Place the desk beside a window when possible, with the light arriving from the side rather than directly in front of or behind the screen. This limits glare and avoids the hard contrast created when a bright window sits immediately behind the display.','Use a blind or translucent curtain to soften direct sun without turning the room dark. The aim is control, not complete exclusion. Notice how the light moves across the desk during the hours when focused work usually happens.']},
{heading:'Build a calm ambient layer',paragraphs:['Ambient light makes the whole room legible after daylight fades. A broad pendant, shaded ceiling fitting, or reflected wall light creates a useful base without making the desk feel like a stage. Choose a warm-neutral colour temperature that is comfortable in the evening and consistent across nearby fittings.','Brightness matters less than balance. If the screen is the brightest object in an otherwise dark room, the eyes repeatedly adapt between extremes. Raise the general level gently, then use task lighting for precision.']},
{heading:'Aim task light at the work',paragraphs:['A task lamp should illuminate paper, tools, and the keyboard without shining into the eyes or reflecting in the monitor. Place it opposite the writing hand to reduce shadows. Keep the shade below eye level and adjust it so the brightest area sits where detailed work occurs.','An articulated arm is valuable because tasks change. Reading a document, drawing, and joining a video call need different positions. A fitting that is easy to move will actually be adjusted rather than tolerated in the wrong place.']},
{heading:'Control contrast and reflection',paragraphs:['Matte desk surfaces are easier to light than polished glass. Screens should sit perpendicular to windows where possible. If reflections remain, change the angle of the lamp before increasing its brightness. Small positional changes often solve discomfort more effectively than a stronger bulb.','Consider the background visible during calls as part of the lighting plan. A softly lit wall or shelf creates depth, while a bright source immediately behind the head causes the camera to underexpose the face.']},
{heading:'Test the complete day',paragraphs:['Review the setup in the morning, late afternoon, and after dark. Check for screen glare, hard shadows, and areas where the eyes feel strained. Save preferred lamp positions or mark them discreetly if several people use the desk.','The successful scheme is not the one with the most fittings. It is the one in which daylight, ambient light, and task light each have a clear job and can be adjusted without interrupting the work.']}
],
'small-room-proportion':[
{heading:'Measure the space between objects',paragraphs:['In a compact room, empty space is functional. Measure the route past the sofa, the clearance needed to pull out a chair, and the arc of every door. Draw these zones before placing furniture. An object that technically fits can still make the room uncomfortable if it consumes the space needed to move.','Prioritise the most repeated route. A generous clear path from the entrance to the main seat often matters more than equal gaps around every object. The arrangement can be asymmetric while still feeling balanced.']},
{heading:'Lower the visual horizon',paragraphs:['Low tables, open legs, and furniture raised slightly from the floor reveal more of the room’s boundaries. The eye can follow the floor and wall behind each piece, which reduces the sense of crowding. This does not mean every object must be delicate. One grounded piece can give the room stability.','Keep the tallest storage close to a wall and away from the main source of daylight. A cabinet that blocks a corner or window edge often feels larger than its dimensions suggest.']},
{heading:'Choose fewer material changes',paragraphs:['A limited palette helps separate functions feel related. Repeat one timber tone or metal finish across the main pieces, then add variation through texture. When every small object introduces a new colour and material, the room becomes visually fragmented.','Matching everything exactly can feel flat, so aim for family resemblance rather than a set. Warm oak can sit beside woven cane and neutral upholstery because the materials share a natural softness without being identical.']},
{heading:'Make storage earn its footprint',paragraphs:['Closed storage is valuable when it holds items that would otherwise remain in circulation. Before adding a cabinet, list what will live inside and confirm that its depth suits those objects. Oversized storage often fills itself with things that were not important enough to organise.','Use the upper part of the wall for infrequently accessed items and keep daily objects between waist and shoulder height. Doors and drawers should open without requiring furniture to move.']},
{heading:'Edit from the doorway',paragraphs:['Stand at the entrance and identify the first three things the eye meets. If they compete, remove or reposition one. A clear foreground, a useful middle distance, and one visual anchor create depth even when the physical distance is limited.','A compact room feels generous when its purpose is clear. Protect movement, control visual weight, and leave some capacity for change. Those decisions matter more than any particular style.']}
],
'designing-workday':[
{heading:'Map the work before the furniture',paragraphs:['List the tasks that occupy most of the week and the objects each task requires. Focused screen work may need one large display and controlled light. Drawing needs clear depth across the desk. Calls need a comfortable camera position and a background that does not demand daily rearrangement.','Allocate the best part of the surface to the most frequent task. Occasional activities can use portable trays or a nearby table rather than permanently occupying the main desk.']},
{heading:'Set the body up first',paragraphs:['Chair height, desk height, and screen position work as one system. Set the chair so the feet are supported, then bring the work surface to a comfortable elbow height. The display should sit at a distance that keeps text readable without leaning forward.','There is no single perfect posture to hold all day. A good setup supports small changes: shifting the chair, standing briefly, looking into the distance, and moving reference material without strain.']},
{heading:'Give cables a deliberate route',paragraphs:['Power should be planned before accessories. Place the desk near enough to a safe outlet and route cables along one controlled edge. Use a removable channel or clips rather than adhesives that damage the finish. Leave enough slack for adjustable lamps and height-changing desks.','Keep chargers that travel with devices easy to remove. Permanent cables can be grouped, but tightly bundling power supplies may trap heat. Good cable management is safe, accessible, and simple to change.']},
{heading:'Store work by state',paragraphs:['Separate active work, reference material, and archived material. A shallow tray can hold the current task, a shelf can keep frequently consulted books visible, and closed storage can contain supplies. This is more useful than organising everything only by object type.','Create one place for unfinished work at the end of the day. Moving it there provides a visible stopping point without requiring every task to be completed or hidden.']},
{heading:'Review friction after one week',paragraphs:['Notice what accumulates, which cable is always in the way, and what you repeatedly stand up to retrieve. These small irritations reveal more than a perfectly staged setup. Adjust one issue at a time and keep what already works.','A successful desk makes beginning and ending easier. It supports the body, keeps the current task clear, and allows the workspace to return to a calm state with a short, repeatable reset.']}
],
'responsible-cane':[
{heading:'Understand the role of the weave',paragraphs:['Cane is strong in tension and useful for breathable doors, panels, and seats. It should not be asked to replace the structural work of a stable timber frame. The rails and joints carry the load while the weave provides a light, flexible surface.','Look for straight frames, even gaps, and edges that are cleanly secured. An unsupported corner or distorted opening places unnecessary stress on the fibres.']},
{heading:'Consistent tension matters',paragraphs:['A panel should feel firm without being rigid. Uneven tension creates local areas that move more than the rest, leading to sagging or broken strands. On machine-woven sheet cane, the spline should sit evenly in a well-cut groove. Hand weaving should show a regular pattern and secure edge work.','Natural cane changes slightly with humidity. A responsible construction allows this movement instead of trapping the panel under excessive tension.']},
{heading:'Source and specification',paragraphs:['Ask suppliers to identify the fibre and its source rather than relying on a generic natural-material label. Responsible harvesting, efficient use of the stem, and durable construction all contribute to the value of the finished product. A renewable material is not automatically sustainable if the object fails quickly.','The surrounding frame matters too. Timber species, finish, joinery, and replaceability should be specified with the same clarity as the cane.']},
{heading:'Everyday care',paragraphs:['Remove dust with a soft brush or low-suction vacuum attachment. Use a lightly damp cloth for marks and dry the area promptly. Avoid soaking the panel, placing it beside strong heat, or loading it with sharp objects that concentrate pressure on a few strands.','Normal indoor humidity helps natural fibres remain resilient. Extremely dry air can make cane brittle, while persistent damp encourages distortion and mould.']},
{heading:'Repair keeps the material useful',paragraphs:['A single damaged strand can sometimes be repaired before the surrounding weave loosens. Larger failures may require the panel to be rewoven or replaced. Frames designed with accessible splines and removable backs make this work possible.','Good cane furniture combines a renewable fibre with construction that respects its limits. The result is light, tactile, ventilated, and capable of remaining in service for many years.']}
],
'shelving-as-architecture':[
{heading:'Read the wall first',paragraphs:['A large shelving system should begin with a measured elevation of the wall. Record skirting, sockets, switches, radiators, doors, and the direction of natural light. These details determine where vertical supports and closed sections can sit without creating awkward gaps.','Consider the wall from neighbouring rooms as well. A strong grid can become a visual endpoint for a hallway or entrance, so its overall proportion matters before individual shelves are filled.']},
{heading:'Establish a useful rhythm',paragraphs:['Repeated bays create order, but perfect repetition is not always useful. Varying one or two widths can accommodate art, records, equipment, or a small work surface. Keep the structural logic visible so that the variation feels deliberate.','Align a few important horizontal lines with nearby architecture, such as a door head or window sill. This makes the shelving feel connected to the room rather than placed in front of it.']},
{heading:'Balance storage and display',paragraphs:['Open shelving works best when it is not treated as a container for everything. Reserve accessible zones for books and objects in regular use. Use closed cabinets for cables, paperwork, and items that create visual noise. Some empty space helps the arrangement remain legible.','Group objects by relationship or use rather than spreading them evenly. A dense shelf beside a quieter one creates a natural rhythm and leaves capacity for new material.']},
{heading:'Plan structure and safety',paragraphs:['Tall systems must be securely fixed to suitable wall structure. Shelf spans, material thickness, and expected loads should be confirmed before installation. Heavy books belong closer to supports and lower in the composition.','Cable routes and ventilation should be planned for any equipment. A closed bay holding electronics needs airflow and accessible power without loose leads crossing open shelves.']},
{heading:'Design for future change',paragraphs:['Adjustable shelf positions and repeatable modules allow the system to respond when books, equipment, or room uses change. Replacement components should be documented and finishes should be repairable. This turns a large installation into adaptable infrastructure.','When shelving becomes architecture, it should make the whole room easier to understand. A clear grid, purposeful variation, safe construction, and room for change matter more than filling every bay on the first day.']}
]};
